osx_image: xcode61
language: objective-c
before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
script: xctool -project MoreCollections.xcodeproj -scheme MoreCollectionsCI  build test -sdk iphonesimulator8.1
