before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
osx_image: xcode61
language: objective-c
xcode_project: MoreCollections.xcodeproj
xcode_scheme: MoreCollectionsTests
xcode_sdk: iphonesimulator8.1